### ISSUE TITLE
'My Retros' page allows users to access retros without any passwords

### ISSUE THREAD

**Issue by akshay-sngh** [davidje13/Refacto#36]
When enabling the `INSECURE_SHARED_ACCOUNT_ENABLED` flag, users can access all retros in the `My Retros` page without a password. However, a password is required when users access the same retros via their respective links.

The expected behavior should be that retros require a password to access retros even from the `My Retros` page.

**Comment by davidje13** [comment]
Setting `INSECURE_SHARED_ACCOUNT_ENABLED` intentionally lets everybody sign in to a single shared account, which will "own" any retros that anybody creates. To avoid issues with (e.g.) retro passwords being lost, users are always allowed to access their own retros, without needing a password.

I can imagine a number of possible use-cases here:

- a fully open deployment (deployed in a private VPN): ideally even the retro passwords would disappear, and everybody should be able to access any existing retro, or create a new retro, without needing any passwords.
  - This could be done by adding a new setting to remove the retro passwords (likely implemented by setting all the retro passwords to a static value and having the frontend know to send this "password" when needed)
- an admin-controlled retro deployment: only "admins" can log in to the "management account", and logging in is not possible for other users (but they can access specific retros using the password).
  - This is possible with the current setup by restricting access to the `/api/open-login` URL ([as documented](https://github.com/davidje13/Refacto/blob/main/docs/SERVICES.md#public-access))
  - In some deployments it may be desirable to again let users access retros without a password, meaning the only restriction is on creating _new_ retros. The same setting mentioned above could be used to achieve this.
- a partially open deployment where anybody can create a new retro, but once created the only way to access it is using the password, even for the person who created it.
  - This seems to be the request here, and could be implemented by blocking the ability to exchange a user token for a retro token (`ApiAuthRouter.ts:21`). It should be quite easy to support, but I'd put it behind a separate environment variable config so that the other use-cases are still possible.
  - it would probably also be desirable to block the "my retros" list entirely when set up like this

**Comment by akshay-sngh** [comment]
You're right, the request is point 3 but having it admin controlled like you mentioned in the doc makes more sense.

I also asked because I am getting `Password breaches lookup error: fetch failed` when I create a new retro with a password and wondered if it was checking for breaches internally first. But upon deleting the db and deploying the app and still seeing the same error, I imagine it's caused by something else.

**Comment by davidje13** [comment]
That error means it's trying to contact the [haveibeenpwned](https://haveibeenpwned.com/Passwords) password checking service to alert users if they enter a common password which is likely to be easily guessed. You can [turn that off if you don't want outbound network traffic](https://github.com/davidje13/Refacto/blob/main/docs/SERVICES.md#haveibeenpwned-password-database).

**Comment by akshay-sngh** [comment]
Thank you! I was able to resolve the issue after adding that env var.

**Comment by davidje13** [comment]
I've implemented a flag `PERMIT_MY_RETROS=false` for the 3rd scenario I mentioned; it disables the "My Retros" list and the ability for a user to access their own retros without a password.

**Comment by akshay-sngh** [comment]
Thank you! I'll add the feature for my team soon.
